[project]
name = "rag-pdf-chat"
version = "0.1.0"
description = "Simple rag app that just reads a pdf and gives some answers"
requires-python = ">=3.10"
dependencies = [
    "gradio",
    "langchain",
    "transformers",
    "torch",
    "sentence-transformers",
    "PyMuPDF",
    "faiss-cpu"
]